<?php
// auto-generated by sfPropelCrud
// date: 2008/04/12 09:31:45
?>
<?php use_helper('Object') ?>

<?php echo form_tag('issue/update', 'id=the_form') ?>

<div class="wrap">

<h2>详细信息</h2>


<?php

#print_r($allIssues);

?>

<?php include_partial('issue/issueEdit10', array('issue' => $issue)) ?>






</form>
