<?php
// auto-generated by sfPropelCrud
// date: 2008/04/12 09:31:45
?>

<div class="wrap">

<form id="posts-filter" action="<?php echo url_for("issue/search") ?>" method="get">
<h2>问题列表</h2>

<p id="post-search">

	<?php if ('search' == $sf_context->getActionName() && $objPager->getNbResults()) : ?>

		<span class="searchResult">
		找到 <strong><?php echo $objPager->getNbResults() ?></strong> 条结果
		以下是第 <strong><?php echo $objPager->getCurrentStart() ?> - <?php echo $objPager->getCurrentCount() ?></strong> 项
		</span>

	<?php endif ?>

	<input type="text" id="post-search-input" name="keyword" value="<?php echo $sf_request->getParameter('keyword', '') ?>" />
	<input type="submit" value="搜索" class="button" />
</p>

<br class="clear" />

<table class="widefat">
<thead>
<tr>

<!--	<th scope="col">ID</th>	-->

	<th scope="col">日期</th>
	<th scope="col">标题</th>
	<th scope="col">提交人</th>

	<th scope="col">优先级</th>
	<th scope="col">处理部门</th>
	<th scope="col">状态</th>

	<th scope="col">操作</th>

</tr>
</thead>
<tbody>


<?php if ($objPager->getNbResults()) : ?>

<?php

#print_r($objPager->getResults());

?>

<?php

$myUserId	= $sf_user->getId();

?>

<?php foreach ($objPager->getResults() as $issue): ?>
<tr id="post-<?php echo $issue['id'] ?>" class="alternate author-self status-publish" valign="top">

<?php if (0) : ?>	<td><a href="<?php echo url_for('issue/show?id=' . $issue['id']) ?>"><?php echo $issue['id'] ?></a></td> <?php endif ?>

	<td><?php echo substr($issue['created_at'], 0, 10) ?></td>
	<td><strong>
	<a class="row-title" href="<?php echo url_for('issue/show?id=' . $issue['id']) ?>" title="<?php echo $issue['title'] ?>"><?php echo mb_strimwidth($issue['title'], 0, sfConfig::get('app_issue_list_title_length'), '...', 'UTF-8') ?></a>
	</strong></td>
	<td><a href="#"><?php echo $issue['username'] ?></a></td>


	<td>
		<?php echo IssuePeer::getPriorityString($issue['priority']) ?>
	</td>
	<td>
		<?php echo IssuePeer::getTypeString($issue['type']) ?>
	</td>
	<td>
		<?php echo IssuePeer::getStatusString($issue['status']) ?>
	</td>
	<td>
		<?php if ($myUserId == $issue['user_id'] && 0 == $issue['locker_id']) : ?>
			<a href="<?php echo url_for('issue/edit?id=' . $issue['id']) ?>" class="myInvolved">编辑</a>
		<?php else : ?>
			<?php if (IssuePeer::STATUS_SUBMITTED == $issue['status']) : ?>
			<?php /* 必须是 submitted 状态，才可以处理 */ ?>
				<a href="<?php echo url_for('issue/edit?do=deal&id=' . $issue['id']) ?>">处理</a>
			<?php endif ?>
		<?php endif ?>
	</td>


</tr>
<?php endforeach; ?>

<?php else : ?>


<tr id="post-0" class="alternate author-self status-publish" valign="top">
	<td colspan="4">
		<span class="searchResult">没有找到匹配的项目！ </span>
	</td>
</tr>

<?php endif ?>



</tbody>
</table>

</form>

<?php

$action		= $sf_context->getActionName();

// 如果是 search ，并且是有效的关键词
$isValidSearch	= 'search' == $action && strlen($keyword = $sf_request->getParameter('keyword', ''));

#var_dump($isValidSearch);

$pageUri	= sprintf(  "issue/%s?%s", $action, ($isValidSearch ? 'keyword=' . urlencode($keyword) . '&' : '')  );

#var_dump($pageUri);

echo include_partial('global/pageNavigation',
				array(
					'pageNavigation' => $objPager,
					'pageUri' => $pageUri
				)
			) ?>

