<?php
// auto-generated by sfPropelCrud
// date: 2008/04/12 09:31:45
?>

<div class="wrap">

<form id="posts-filter" action="<?php echo url_for("issue/search") ?>" method="get">
<h2>问题列表</h2>

<p id="post-search">

	<?php if ($objPager->getNbResults()) : ?>

		<span class="searchResult">
		找到 <?php echo $objPager->getNbResults() ?> 条结果
		以下是第 <?php echo $objPager->getCurrentStart() ?> - <?php echo $objPager->getCurrentCount() ?> 项
		</span>

	<?php endif ?>

	<input type="text" id="post-search-input" name="keyword" value="<?php echo htmlspecialchars($sf_request->getParameter('keyword', '')) ?>" />
	<input type="submit" value="搜索" class="button" />
</p>

<br class="clear" />

<table class="widefat">
<thead>
<tr>

	<th scope="col">日期</th>
	<th scope="col">标题</th>
	<th scope="col">提交人</th>
	<th scope="col">状态</th>

</tr>
</thead>
<tbody>


<?php if ($objPager->getNbResults()) : ?>

<?php foreach ($objPager->getResults() as $issue): ?>
<tr id="post-<?php echo $issue['id'] ?>" class="alternate author-self status-publish" valign="top">

	<td><?php echo substr($issue['created_at'], 0, 10) ?></td>

	<td><strong>
	<a class="row-title" href="#" title="<?php echo $issue['title'] ?>"><?php echo mb_strimwidth($issue['title'], 0, 80, '...', 'UTF-8') ?></a>
	</strong></td>

	<td><a href="#"><?php echo $issue['username'] ?></a></td>
	<td><a href="#"><?php echo $issue['user_id'] ?></a></td>

</tr>
<?php endforeach; ?>

<?php else : ?>


<tr id="post-0" class="alternate author-self status-publish" valign="top">
	<td colspan="4">
		<span class="searchResult">没有找到与 <strong><?php echo htmlspecialchars($sf_request->getParameter('keyword', '')) ?></strong> 匹配的结果！ </span>
	</td>
</tr>

<?php endif ?>



</tbody>
</table>

</form>

<div id="ajax-response"></div>

<?php

$action		= $sf_context->getActionName();

// 如果是 search ，并且是有效的关键词
$isValidSearch	= 'search' == $action && strlen($keyword = $sf_request->getParameter('keyword', ''));

#var_dump($isValidSearch);

$pageUri	= sprintf(  "issue/%s?%s", $action, ($isValidSearch ? 'keyword=' . urlencode($keyword) . '&' : '')  );


echo include_partial('global/pageNavigation',
				array(
					'pageNavigation' => $objPager,
					'pageUri' => $pageUri
				)
			) ?>

