<?php
// auto-generated by sfPropelCrud
// date: 2008/04/12 09:31:45
?>

<div class="wrap">

<form id="posts-filter" action="" method="get">
<h2>Manage Posts</h2>



<br class="clear" />

<table class="widefat">
<thead>
<tr>

	<th scope="col">日期</th>
	<th scope="col">标题</th>
	<th scope="col">提交人</th>
	<th scope="col">状态</th>

</tr>
</thead>
<tbody>


<?php foreach ($objPager->getResults() as $issue): ?>
<tr id='post-<?php echo $issue['id'] ?>' class='alternate author-self status-publish' valign="top">

	<td><?php echo substr($issue['created_at'], 0, 10) ?></td>

	<td><strong>
	<a class="row-title" href="#" title="<?php echo $issue['title'] ?>"><?php echo mb_strimwidth($issue['title'], 0, 80, '...', 'UTF-8') ?></a>
	</strong></td>

	<td><a href="#"><?php echo $issue['username'] ?></a></td>
	<td><a href="#"><?php echo $issue['user_id'] ?></a></td>

</tr>
<?php endforeach; ?>
	</tbody>
</table>

</form>

<div id="ajax-response"></div>

<div class="tablenav">

<?php if (0) : ?>
<div class='tablenav-pages'><span class='page-numbers current'>1</span>
<a class='page-numbers' href='/wp-admin/edit.php?paged=2'>2</a>
<a class='page-numbers' href='/wp-admin/edit.php?paged=3'>3</a>
<span class='page-numbers dots'>...</span>
<a class='page-numbers' href='/wp-admin/edit.php?paged=8'>8</a>
<a class='next page-numbers' href='/wp-admin/edit.php?paged=2'>Next &raquo;</a></div>
<br class="clear" />
</div>
<?php endif ?>

<?php echo include_partial('global/pageNavigation', array('pageNavigation' => $objPager, 'pageUri' => 'issue/list?')) ?>

<br class="clear" />


</div>
