<?php
// auto-generated by sfPropelCrud
// date: 2008/04/12 09:31:45
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $issue->getId() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $issue->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $issue->getUpdatedAt() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $issue->getUserId() ?></td>
</tr>
<tr>
<th>Type: </th>
<td><?php echo $issue->getType() ?></td>
</tr>
<tr>
<th>Status: </th>
<td><?php echo $issue->getStatus() ?></td>
</tr>
<tr>
<th>Priority: </th>
<td><?php echo $issue->getPriority() ?></td>
</tr>
<tr>
<th>Title: </th>
<td><?php echo $issue->getTitle() ?></td>
</tr>
<tr>
<th>Description: </th>
<td><?php echo $issue->getDescription() ?></td>
</tr>
<tr>
<th>Solution: </th>
<td><?php echo $issue->getSolution() ?></td>
</tr>
<tr>
<th>Reference: </th>
<td><?php echo $issue->getReference() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'issue/edit?id='.$issue->getId()) ?>
&nbsp;<?php echo link_to('list', 'issue/list') ?>
