<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 13:43:24
?>
<?php use_helper('Object') ?>

<?php echo form_tag('maintance/update') ?>

<?php echo object_input_hidden_tag($maintance, 'getId') ?>

<table>
<tbody>
<tr>
  <th>User*:</th>
  <td><?php echo object_input_tag($maintance, 'getUserId', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Maintance detail*:</th>
  <td><?php echo object_textarea_tag($maintance, 'getMaintanceDetail', array (
  'size' => '30x3',
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($maintance->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'maintance/delete?id='.$maintance->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'maintance/show?id='.$maintance->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'maintance/list') ?>
<?php endif; ?>
</form>
