<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 13:43:24
?>
<h1>maintance</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Created at</th>
  <th>User</th>
  <th>Maintance detail</th>
</tr>
</thead>
<tbody>
<?php foreach ($maintances as $maintance): ?>
<tr>
    <td><?php echo link_to($maintance->getId(), 'maintance/show?id='.$maintance->getId()) ?></td>
      <td><?php echo $maintance->getCreatedAt() ?></td>
      <td><?php echo $maintance->getUserId() ?></td>
      <td><?php echo $maintance->getMaintanceDetail() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'maintance/create') ?>
