default:
  http_metas:
    content-type: text/html

  metas:
    title:        任子行客服系统
    robots:       index, follow
    description:  Leakon project
    keywords:     Leakon, project
    language:     en

  stylesheets:    []

  javascripts:    []

  has_layout:     on
  layout:         layout_joomla
