<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/08/20 17:08:02

return array(
'Table' => new SofavDB_Symfony(array (
  'dsn' => 'Table: mysql://dmc071197:a5j1m7c3j5@dmc-07.hichina.com:3306/dmc071197_db?encoding=utf8&persistent=on',
  'name' => 'Table',
)),);
