<?php
// auto-generated by sfSecurityConfigHandler
// date: 2009/08/20 17:08:03
$this->security = array (
  'login' => 
  array (
    'is_secure' => false,
  ),
  'dologin' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'admin',
  ),
);
