<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 13:42:54
?>
<h1>product</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Created at</th>
  <th>Ordered at</th>
  <th>Installed at</th>
  <th>Completed at</th>
  <th>Warranty begin</th>
  <th>Warranty end</th>
  <th>Sale contact</th>
  <th>Sale phone</th>
  <th>Name</th>
  <th>Customer</th>
  <th>User</th>
  <th>Style</th>
  <th>Use type</th>
  <th>Amount</th>
  <th>Install detail</th>
</tr>
</thead>
<tbody>
<?php foreach ($products as $product): ?>
<tr>
    <td><?php echo link_to($product->getId(), 'product/show?id='.$product->getId()) ?></td>
      <td><?php echo $product->getCreatedAt() ?></td>
      <td><?php echo $product->getOrderedAt() ?></td>
      <td><?php echo $product->getInstalledAt() ?></td>
      <td><?php echo $product->getCompletedAt() ?></td>
      <td><?php echo $product->getWarrantyBegin() ?></td>
      <td><?php echo $product->getWarrantyEnd() ?></td>
      <td><?php echo $product->getSaleContact() ?></td>
      <td><?php echo $product->getSalePhone() ?></td>
      <td><?php echo $product->getName() ?></td>
      <td><?php echo $product->getCustomerId() ?></td>
      <td><?php echo $product->getUserId() ?></td>
      <td><?php echo $product->getStyle() ?></td>
      <td><?php echo $product->getUseType() ?></td>
      <td><?php echo $product->getAmount() ?></td>
      <td><?php echo $product->getInstallDetail() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'product/create') ?>
