<?php
// auto-generated by sfPropelCrud
// date: 2008/04/12 09:31:44
?>
<?php

/**
 * issue actions.
 *
 * @package    renzixing
 * @subpackage issue
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class issueActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('issue', 'list');
  }


  public function executeShowxxxx()
  {
    $this->issue = IssuePeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->issue);
  }

  public function executeCreate()
  {
    $this->issue = new Issue();

    $this->setTemplate('edit');
  }



  public function executeDelete()
  {
    $issue = IssuePeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($issue);

    $issue->delete();

    return $this->redirect('issue/list');
  }


	public function executeList() {
		// 带翻页的列表
		$this->objPager = IssuePeer::listIssues($this->getRequestParameter('page', 1));

	}

	public function executeSearch() {
		// 带翻页的列表
		$this->setTemplate('list');
		$this->objPager = IssuePeer::searchIssues($this->getRequestParameter('page', 1));

	}

	// 与我有关的
	public function executeInvolved() {
		// 带翻页的列表
		$this->setTemplate('list');
		$this->objPager = IssuePeer::searchIssues($this->getRequestParameter('page', 1));

	}



	// 浏览 Issue
	public function executeShow() {
	#	$this->issue = IssuePeer::retrieveByPk($this->getRequestParameter('id'));
	#	$this->forward404Unless($this->issue);

	#	$this->setTemplate('edit');
	#	$this->justViewIssues	= true;
		$this->allIssues	= IssuePeer::getGroupedIssue($this->getRequestParameter('id'));

	}

	// 编辑 or 处理 Issue
	public function executeEdit() {


		$this->allIssues	= IssuePeer::getGroupedIssue($this->getRequestParameter('id'));

		$this->issue	= $this->allIssues['Agency'];


	#	$this->issue = IssuePeer::retrieveByPk($this->getRequestParameter('id'));

	#	$this->issue	= $this->allIssues[IssuePeer::TYPE_AGENCY];

	#	var_dump($this->allIssues);

	#	$this->forward404Unless($this->issue);

	#	$this->allIssues[$this->issue->getType()]	= $this->issue;

		// 默认禁止编辑
		$this->allowEdit	= false;

/*
		if (0 && 'deal' == $this->getRequestParameter('do') && 0 == $this->issue->getLockerId()) {
			// 可以编辑
			$this->allowEdit	= true;
			$this->issue->setLockerId($this->getUser()->getId());
			$this->issue->save();


			$arrLevelMap	= IssuePeer::getLevelMap($this->issue->getType());
			$issue		= new Issue();

			$issue->setType($arrLevelMap['next']);
			$this->allIssues[$arrLevelMap['next']]	= $issue;

		}
*/


	}



	public function executeUpdate() {

		if (!$this->getRequestParameter('id')) {
			$issue = new Issue();
		} else {
			$issue = IssuePeer::retrieveByPk($this->getRequestParameter('id'));
			$this->forward404Unless($issue);
		}

		// 公共部分
		$issue->setId($this->getRequestParameter('id'));
		$issue->setUserId($this->getUser()->getId());
		$issue->setPriority($this->getRequestParameter('priority'));
		$issue->setTitle($this->getRequestParameter('title'));
		$issue->setDescription($this->getRequestParameter('description'));
		$issue->setSolution($this->getRequestParameter('solution'));;
		$issue->setReference($this->getRequestParameter('reference'));
		$issue->setStatus($this->getRequestParameter('status'));
		$issue->setType($this->getRequestParameter('type'));

		$typeString	= $issue->getTypeString();
		$method		= sprintf("saveEdit%s", $typeString);

		$issue->$method($this);

		$issue->handleDecision();


		#    var_dump($this->getRequestParameter('status'));
		/*

		$issue->setId($this->getRequestParameter('id'));
		$issue->setUserId($this->getRequestParameter('user_id'));
		$issue->setPriority($this->getRequestParameter('priority'));
		$issue->setTitle($this->getRequestParameter('title'));
		$issue->setDescription($this->getRequestParameter('description'));
		$issue->setSolution($this->getRequestParameter('solution'));
		$issue->setReference($this->getRequestParameter('reference'));


		$issue->setType($this->getRequestParameter('type'));
		$issue->setStatus($this->getRequestParameter('status'));

		$issue->save();
		*/


		return $this->redirect('issue/edit?id='.$issue->getBaseId());


	#	return $this->redirect('issue/show?id='.$issue->getId());
	}

}
