<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 08:35:16
?>
<?php use_helper('Object') ?>

<?php echo form_tag('customer/update') ?>

<?php echo object_input_hidden_tag($customer, 'getId') ?>

<table>
<tbody>
<tr>
  <th>客户名称*:</th>
  <td><?php echo object_input_tag($customer, 'getName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>区域*:</th>
  <td><?php echo object_input_tag($customer, 'getArea', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>城市*:</th>
  <td><?php echo object_input_tag($customer, 'getCity', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>联系人一*:</th>
  <td><?php echo object_input_tag($customer, 'getFirstContact', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>联系人一 电话 a*:</th>
  <td><?php echo object_input_tag($customer, 'getFirstPhoneA', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>联系人一 电话 b*:</th>
  <td><?php echo object_input_tag($customer, 'getFirstPhoneB', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>联系人一 电话 c*:</th>
  <td><?php echo object_input_tag($customer, 'getFirstPhoneC', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>联系人二*:</th>
  <td><?php echo object_input_tag($customer, 'getSecondContact', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>联系人二 电话 a*:</th>
  <td><?php echo object_input_tag($customer, 'getSecondPhoneA', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>联系人二 电话 b*:</th>
  <td><?php echo object_input_tag($customer, 'getSecondPhoneB', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>联系人二 电话 c*:</th>
  <td><?php echo object_input_tag($customer, 'getSecondPhoneC', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>客户地址*:</th>
  <td><?php echo object_input_tag($customer, 'getAddress', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>邮编*:</th>
  <td><?php echo object_input_tag($customer, 'getPostCode', array (
  'size' => 80,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('保存') ?>
<?php if ($customer->getId()): ?>
  &nbsp;<?php echo link_to('删除', 'customer/delete?id='.$customer->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('返回', 'customer/show?id='.$customer->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('返回列表', 'customer/list') ?>
<?php endif; ?>
</form>
