<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 13:42:54
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $product->getId() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $product->getCreatedAt() ?></td>
</tr>
<tr>
<th>Ordered at: </th>
<td><?php echo $product->getOrderedAt() ?></td>
</tr>
<tr>
<th>Installed at: </th>
<td><?php echo $product->getInstalledAt() ?></td>
</tr>
<tr>
<th>Completed at: </th>
<td><?php echo $product->getCompletedAt() ?></td>
</tr>
<tr>
<th>Warranty begin: </th>
<td><?php echo $product->getWarrantyBegin() ?></td>
</tr>
<tr>
<th>Warranty end: </th>
<td><?php echo $product->getWarrantyEnd() ?></td>
</tr>
<tr>
<th>Sale contact: </th>
<td><?php echo $product->getSaleContact() ?></td>
</tr>
<tr>
<th>Sale phone: </th>
<td><?php echo $product->getSalePhone() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $product->getName() ?></td>
</tr>
<tr>
<th>Customer: </th>
<td><?php echo $product->getCustomerId() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $product->getUserId() ?></td>
</tr>
<tr>
<th>Style: </th>
<td><?php echo $product->getStyle() ?></td>
</tr>
<tr>
<th>Use type: </th>
<td><?php echo $product->getUseType() ?></td>
</tr>
<tr>
<th>Amount: </th>
<td><?php echo $product->getAmount() ?></td>
</tr>
<tr>
<th>Install detail: </th>
<td><?php echo $product->getInstallDetail() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'product/edit?id='.$product->getId()) ?>
&nbsp;<?php echo link_to('list', 'product/list') ?>
