default:
  http_metas:
    content-type: text/html

  metas:
    title:        中国林业生物质能源网 - 管理后台
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [admin.css, -global.css, -style.css]

  javascripts:    []

  has_layout:     on
  layout:         layout_admin
