<?php
// auto-generated by sfRoutingConfigHandler
// date: 2009/08/20 17:08:02
return array(
'homepage' => new sfRoute('/', array (
  'module' => 'frame',
  'action' => 'index',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
