<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2009/08/20 17:08:03
return array(

  // sfProtoculousPlugin_module_libs

  // sfProtoculousPlugin_lib

  // sfCompat10Plugin_module_libs

  // sfCompat10Plugin_lib
  'sfEzComponentsBridge' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/bridge/sfEzComponentsBridge.class.php',
  'sfZendFrameworkBridge' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/bridge/sfZendFrameworkBridge.class.php',
  'sfProcessCache' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/cache/sfProcessCache.class.php',
  'sfValidatorConfigHandler' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/config/sfValidatorConfigHandler.class.php',
  'sfActionException' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/exception/sfActionException.class.php',
  'sfValidatorException' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/exception/sfValidatorException.class.php',
  'sfFillInFormFilter' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/filter/sfFillInFormFilter.class.php',
  'sfValidationExecutionFilter' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/filter/sfValidationExecutionFilter.class.php',
  'sfRequestCompat10' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/request/sfRequestCompat10.class.php',
  'sfMail' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/sfMail.class.php',
  'sfFillInForm' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/util/sfFillInForm.class.php',
  'sfCallbackValidator' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/validator/sfCallbackValidator.class.php',
  'sfCompareValidator' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/validator/sfCompareValidator.class.php',
  'sfDateValidator' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/validator/sfDateValidator.class.php',
  'sfEmailValidator' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/validator/sfEmailValidator.class.php',
  'sfFileValidator' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/validator/sfFileValidator.class.php',
  'sfNumberValidator' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/validator/sfNumberValidator.class.php',
  'sfRegexValidator' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/validator/sfRegexValidator.class.php',
  'sfStringValidator' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/validator/sfStringValidator.class.php',
  'sfUrlValidator' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/validator/sfUrlValidator.class.php',
  'sfValidator' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/validator/sfValidator.class.php',
  'sfValidatorManager' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/validator/sfValidatorManager.class.php',
  'PHPMailer' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/vendor/phpmailer_xxxxx/class.phpmailer.php',
  'SMTP' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/vendor/phpmailer_xxxxx/class.smtp.php',
  'sfMailView' => 'D:/Leakon/code/project/symfony/sofav_2008_2/stable/symfony-1.2.4/lib/plugins/sfCompat10Plugin/lib/view/sfMailView.class.php',

  // project
  'SimpleSessionPdo' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/Session/SimpleSessionPdo.class.php',
  'SimpleSymfonyUser' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/Session/SimpleSymfonyUser.class.php',
  'UserSession' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/Session/UserSession.class.php',
  'Simple_Pager_Base' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/SofavDB/SimplePager.php',
  'Simple_Pager' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/SofavDB/SimplePager.php',
  'SofavDB_Criteria' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/SofavDB/SofavDB_Criteria.php',
  'SofavDB_Debug_PDO' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/SofavDB/SofavDB_Debug_PDO.php',
  'SofavDB_Debug_PDO_Statement' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/SofavDB/SofavDB_Debug_PDO.php',
  'SofavDB_Manager' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/SofavDB/SofavDB_Manager.php',
  'SofavDB_Pager' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/SofavDB/SofavDB_Pager.php',
  'SofavDB_Record' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/SofavDB/SofavDB_Record.php',
  'SofavDB_SQL' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/SofavDB/SofavDB_SQL.php',
  'SofavDB_Symfony' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/SofavDB/SofavDB_Symfony.php',
  'SofavDB_Table' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/SofavDB/SofavDB_Table.php',
  'SofavDB_Tools' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/SofavDB/SofavDB_Tools.php',
  'Table_articles' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/SofavDB_Model/sf_table_articles.class.php',
  'Table_categories' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/SofavDB_Model/sf_table_categories.class.php',
  'Table_messages' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/SofavDB_Model/sf_table_messages.class.php',
  'Table_users' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/SofavDB_Model/sf_table_users.class.php',
  'ArrayUtil' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/Utility/ArrayUtil.class.php',
  'Array_Util' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/Utility/Array_Util.class.php',
  'CnroConstant' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/Utility/CnroConstant.class.php',
  'Custom_Conf' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/Utility/Custom_Conf.class.php',
  'Custom_Homepage' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/Utility/Custom_Homepage.class.php',
  'Debug' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/Utility/Debug.class.php',
  'Fm' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/Utility/Fm.class.php',
  'IMG' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/Utility/IMG.class.php',
  'MyLog' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/Utility/MyLog.class.php',
  'S' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/Utility/S.class.php',
  'Util' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/lib/Utility/Util.class.php',

  // project_model

  // application
  'BaseBrandActions' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/apps/admin/lib/actions/actions_brand.class.php',
  'myUser' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/apps/admin/lib/myUser.class.php',
  'ActionSecurity' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/apps/admin/lib/util/ActionSecurity.php',
  'ActionItem' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/apps/admin/lib/util/actions_item.class.php',
  'ActionsUtil' => 'D:/Leakon/code/project/new_service/cnro/hosting/proj_cn/apps/admin/lib/util/actions_util.class.php',

  // modules
);
