<?php
// auto-generated by sfPropelCrud
// date: 2008/04/12 06:55:09
?>
<h1>user</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Created at</th>
  <th>Role</th>
  <th>Username</th>
  <th>Password</th>
  <th>Email</th>
</tr>
</thead>
<tbody>
<?php foreach ($users as $user): ?>
<tr>
    <td><?php echo link_to($user->getId(), 'user/show?id='.$user->getId()) ?></td>
      <td><?php echo $user->getCreatedAt() ?></td>
      <td><?php echo $user->getRole() ?></td>
      <td><?php echo $user->getUsername() ?></td>
      <td><?php echo $user->getPassword() ?></td>
      <td><?php echo $user->getEmail() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'user/create') ?>
