<?php
// auto-generated by sfPropelCrud
// date: 2008/04/12 06:55:09
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $user->getId() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $user->getCreatedAt() ?></td>
</tr>
<tr>
<th>Role: </th>
<td><?php echo $user->getRole() ?></td>
</tr>
<tr>
<th>Username: </th>
<td><?php echo $user->getUsername() ?></td>
</tr>
<tr>
<th>Password: </th>
<td><?php echo $user->getPassword() ?></td>
</tr>
<tr>
<th>Email: </th>
<td><?php echo $user->getEmail() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'user/edit?id='.$user->getId()) ?>
&nbsp;<?php echo link_to('list', 'user/list') ?>
