default:
  http_metas:
    content-type: text/html

  metas:
    title:        天津森罗科技发展有限责任公司
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, global.css, style.css]

  javascripts:    [main.js]

  has_layout:     on
  layout:         layout
