#dev:
#  propel:
#    param:
#      classname:  DebugPDO
#
#test:
#  propel:
#    param:
#      classname:  DebugPDO
#
#all:
#  propel:
#    class:        sfPropelDatabase
#    param:
#      classname:  PropelPDO
#      dsn:        mysql:dbname=ns_cnro;host=localhost
#      username:   root
#      password:
#      encoding:   utf8
#      persistent: true
#      pooling:    true


dev:
  Table:
    class:          SofavDB_Symfony
    param:
      dsn:          Table: mysql://dmc071197:a5j1m7c3j5@dmc-07.hichina.com:3306/dmc071197_db?encoding=utf8&persistent=on

prod:
  Table:
    class:          SofavDB_Symfony
    param:
      dsn:          Table: mysql://dmc071197:a5j1m7c3j5@dmc-07.hichina.com:3306/dmc071197_db?encoding=utf8&persistent=on

test:
  Table:
    class:          SofavDB_Symfony
    param:
      dsn:          Table: mysql://dmc071197:a5j1m7c3j5@dmc-07.hichina.com:3306/dmc071197_db?encoding=utf8&persistent=on
