#dev:
#  propel:
#    param:
#      classname:  DebugPDO
#
#test:
#  propel:
#    param:
#      classname:  DebugPDO
#
#all:
#  propel:
#    class:        sfPropelDatabase
#    param:
#      classname:  PropelPDO
#      dsn:        mysql:dbname=forest;host=localhost
#      username:   root
#      password:
#      encoding:   utf8
#      persistent: true
#      pooling:    true


dev:
  Table:
    class:          SofavDB_Symfony
    param:
      dsn:          Table: mysql://root:123456@localhost:3306/forest?encoding=utf8&persistent=on&debug=on

prod:
  Table:
    class:          SofavDB_Symfony
    param:
      dsn:          Table: mysql://root:123456@localhost:3306/forest?encoding=utf8&persistent=on

test:
  Table:
    class:          SofavDB_Symfony
    param:
      dsn:          Table: mysql://root:123456@localhost:3306/forest?encoding=utf8&persistent=on&debug=on
