<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 13:43:24
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $maintance->getId() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $maintance->getCreatedAt() ?></td>
</tr>
<tr>
<th>User: </th>
<td><?php echo $maintance->getUserId() ?></td>
</tr>
<tr>
<th>Maintance detail: </th>
<td><?php echo $maintance->getMaintanceDetail() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'maintance/edit?id='.$maintance->getId()) ?>
&nbsp;<?php echo link_to('list', 'maintance/list') ?>
