<?php
// auto-generated by sfPropelCrud
// date: 2008/04/20 13:43:24
?>

<?php

$m = $maintance->getMaintanceDetail()->getRaw('detail');

#var_dump($arrMaintance);

?>

<table>
<tbody>




<tr>
	<th>服务器厂商及型号</th>
	<td><?php echo HelperView::getArray($m, 'server_info') ?></td>

	<th>客服电话</th>
	<td><?php echo HelperView::getArray($m, 'support_phone') ?></td>
</tr>


<tr>
	<th>主板类型</th>
	<td><?php echo HelperView::getArray($m, 'main_board_info') ?></td>

	<th>支持CPU个数</th>
	<td><?php echo HelperView::getArray($m, 'support_cpu_amount') ?></td>
</tr>

<tr>
	<th>内存个数</th>
	<td><?php echo HelperView::getArray($m, 'memory_amount') ?></td>

	<th>内存大小</th>
	<td><?php echo HelperView::getArray($m, 'memory_size') ?></td>
</tr>


<tr>
	<th>CPU个数</th>
	<td><?php echo HelperView::getArray($m, 'cpu_quantity') ?></td>

	<th>CPU型号</th>
	<td><?php echo HelperView::getArray($m, 'cpu_style') ?></td>
</tr>
<tr>
	<th>CPU频率</th>
	<td><?php echo HelperView::getArray($m, 'cpu_frequncy') ?></td>

	<th>CPU核心类型</th>
	<td><?php echo HelperView::getArray($m, 'cpu_core') ?></td>
</tr>

<tr>
	<th>硬盘类型</th>
	<td><?php echo HelperView::getArray($m, 'hd_style') ?></td>

	<th>硬盘数量</th>
	<td><?php echo HelperView::getArray($m, 'hd_quantiry') ?></td>
</tr>
<tr>
	<th>硬盘容量</th>
	<td><?php echo HelperView::getArray($m, 'hd_size') ?></td>

	<th>RAID</th>
	<td><?php echo HelperView::getArray($m, 'hd_raid') ?></td>
</tr>

<tr>
	<th>硬盘备注</th>
	<td colspan="3"><?php echo HelperView::getArray($m, 'hd_comment') ?></td>
</tr>




<tr>
	<th>网卡数量</th>
	<td><?php echo HelperView::getArray($m, 'net_card_quantity') ?></td>

	<th>网卡传输</th>
	<td></td>
</tr>


<tr>
	<th>光驱接口</th>
	<td colspan="3"></td>
</tr>


<tr>
	<th>操作系统</th>
	<td colspan="3"></td>
</tr>
<tr>
	<th>特殊功能</th>
	<td colspan="3"></td>
</tr>
<tr>
	<th>维护建议</th>
	<td colspan="3"></td>
</tr>




</tbody>
</table>
<hr />
<?php echo link_to('edit', 'maintance/edit?id='.$maintance->getId()) ?>
&nbsp;<?php echo link_to('list', 'maintance/list') ?>
