default:
  http_metas:
    content-type: text/html

  metas:
    title:        COLIBRI
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [global.css]

  javascripts:    [jquery-1.2.6.min.js, function.js?20101206-2, main.js]

  has_layout:     on
  layout:         layout
